### ISSUE TITLE
「missing」が挟まるケース

### ISSUE THREAD

**Issue by amenohimo** [fgosc/fgosccnt#177]
![image](https://user-images.githubusercontent.com/6458565/92177581-c1eacc80-ee7b-11ea-8fcb-f4a34e357185.png)

```
filename,ドロ数,報酬QP(+9400),礼装,冠,狂秘,チェーンソー(x3),野菜(x3),薪(x3),QP(+50万)
合計,,1,0,2,1,10,17,8,1
R:\IMG_1254.jpg,20+,1,,2,1,10,7,,
missing,,,,,,,,,
R:\IMG_1255.jpg,19,,,,,,10,8,1
```

品質 70
サブサンプリング 4:2:0
グレイスケール化 ITU-R BT.709 (Red: 0.22125 Green: 0.7154 Blue: 0.0721)

IMG_1254
![IMG_1254](https://user-images.githubusercontent.com/6458565/92177660-e34bb880-ee7b-11ea-9505-7430f1611034.jpg)

IMG_1255
![IMG_1255](https://user-images.githubusercontent.com/6458565/92177662-e47ce580-ee7b-11ea-8551-76033ecb1c67.jpg)

**Comment by fgophi** [comment]
@max747 
pageinfo.py が2ページ目を1ページだと返しているのが原因だけど、グレースケールだと対応していません?
```
$ python pageinfo.py page IMG_1255.jpg
IMG_1255.jpg,1,1,0
```

**Comment by max747** [comment]
グレースケールは検証したことがないので、うまくいかないケースがあるかもしれません。当該画像については調べてみます。

**Comment by max747** [comment]
```
[DEBUG] scrollable area candidate: (x, y, width, height) = (0, 0, 334, 746)
[DEBUG] th 19: scrollbar was found, but scrollable area is not found, retry
[DEBUG] scrollable area candidate: (x, y, width, height) = (20, 253, 124, 135)
[DEBUG] scrollable area candidate: (x, y, width, height) = (96, 129, 123, 440)
[DEBUG] scrollable area candidate: (x, y, width, height) = (20, 118, 124, 122)
[DEBUG] scrollable area candidate: (x, y, width, height) = (0, 0, 334, 747)
[DEBUG] th 18: scrollbar was found, but scrollable area is not found, retry
[DEBUG] writing debug image: debugimages/page/gray_q70.jpg
[DEBUG] pagenum: 1, pages: 1, lines: 0
gray_q70.jpg,1,1,0
```

スクロール可能領域が検出できていないようです。

**Comment by fgophi** [comment]
スクロール可能領域が検出できないのは相当ですね

基本カラーJPEGの場合で品質80未満のやつですぐ直せそうにないものは直せないです(追及するリソースをそこに使うメリットが少ないため)
グレースケールの場合はグレースケールJPEG化での容量減の効果が(開発陣の価値観では)たいして無いのでなおさらです

**Comment by amenohimo** [comment]
ご検証いただき、ありがとうございます

今後の報告はカラーで品質80以上のものに限定することにいたします
