### ISSUE TITLE
pageinfoが正しい頁数を返さない

### ISSUE THREAD

**Issue by fgophi** [fgosc/fgosccnt#258]
1ページで完結しているバトルリザルトのスクショなのに2ページのうちの1ページ目だと誤認識している

```
$ python ../pageinfo.py page IMG_6210.jpg
IMG_6210.jpg,1,2,4

$ python ../pageinfo.py page IMG_6219.jpg
IMG_6219.jpg,1,2,3
```
![IMG_6210](https://user-images.githubusercontent.com/62515228/105580123-dea58380-5dcd-11eb-83b7-fd15ebc60856.jpg)
![IMG_6219](https://user-images.githubusercontent.com/62515228/105580134-f11fbd00-5dcd-11eb-9909-498d34dcab5a.jpg)

**Comment by max747** [comment]
村正のマントでスクロール可能領域が通常よりも広がってしまい、結果として比率の計算で誤差が生じ意図しない結果を生む。#333 で解消予定。

![image](https://user-images.githubusercontent.com/696577/139524996-133a750b-ffc6-4ed9-8981-5d2f6078e1bd.png)

**Comment by max747** [comment]
最新バージョンでは修正されているはず。
