### ISSUE TITLE
剣猛火が槍猛火や弓猛火、剣大火が術大火に化ける

### ISSUE THREAD

**Issue by amenohimo** [fgosc/fgosccnt#262]
周回場所：平安京 朱雀門

419.PNG
![0419](https://user-images.githubusercontent.com/6458565/117016254-7d2a7480-ad2d-11eb-84a1-5d7b64b45445.PNG)

687.PNG
![0687](https://user-images.githubusercontent.com/6458565/117016697-eca06400-ad2d-11eb-896b-36fafc247565.PNG)

0365.PNG
![0365](https://user-images.githubusercontent.com/6458565/117017361-7f410300-ad2e-11eb-95e1-1dbe1ff04ac8.PNG)

![image](https://user-images.githubusercontent.com/6458565/117018105-2aea5300-ad2f-11eb-81ea-644afd26e65a.png)

**Comment by max747** [comment]
本件に対応する解析結果はこちらでしょうか？
https://fgojunks.max747.org/fgosccnt/results/5bba90b3-d155-4141-88f9-163d41e8e543/

**Comment by fgophi** [comment]
@amenohimo
これは情報ウィンドウがクラス判定を行っている画像部分まで食い込んでいるため起こっている問題です

ただ、クラス判定を行っている箇所はもともと領域がかなり小さいので、ここを直すと今まで判別正解できていた画像を誤認識する可能性があるので判定領域を小さく修正したあとに問題が起こらないかの検証を工程数をかけてかなり慎重にやらないといけません

検証用の画像も新規で用意しないといけないので、すぐには直せない今後の課題ということになります

**Comment by amenohimo** [comment]
ファイさん、まっくすさん、調べて頂きありがとうございます

@max747
はい、その解析結果です

ローカルでの実行は重複画像や周回数を把握するために行っていました
Web版で周回数が2回分違うのは、キリよく1000周で報告することにし、残りは次回報告時分のディレクトリに移動して減らしたためです
枚数が4桁だったため、Webでの解析時にはファイル名の頭に0を1桁加えています

クエスト名が自動で認識されなかったため、ローカル実行時のデータを調べて、アイテム名が化けていることに気付きました
Excelの画面はローカルのデータを調べていたときのものです


@fgophi 
了解です、大変な修正になりそうですね

UI変更前の枚数の方が多いですが、1334 x 750 と 2560 x 1600 の画像が多少あります
![res](https://user-images.githubusercontent.com/6458565/117086546-c3142680-ad87-11eb-92b4-de3c57893969.jpg)

必要なものがありましたら、提供できるかもしれないので仰ってください

**Comment by amenohimo** [comment]
テスト用のサンプルにどうぞ

![image](https://user-images.githubusercontent.com/6458565/127778145-986400f9-547d-40bd-9f3f-0b9c7924f775.png)


08946
![08946](https://user-images.githubusercontent.com/6458565/127778096-e42bd1e8-0dd5-4cce-b291-7cd516edbab3.jpg)

10591
![10591](https://user-images.githubusercontent.com/6458565/127778100-eeba0a4c-ca91-4152-bac6-776cf1c98b3e.jpg)

**Comment by fgophi** [comment]
@amenohimo 
ようやくこの問題を修正しました
