### ISSUE TITLE
not validが発生する

### ISSUE THREAD

**Issue by amenohimo** [fgosc/fgosccnt#263]
![image](https://user-images.githubusercontent.com/6458565/117118111-5884da00-adcb-11eb-9d8c-c72591e5b4df.png)

IMG_4516.PNG
![IMG_4516](https://user-images.githubusercontent.com/6458565/117117833-f5934300-adca-11eb-9c07-e1b53f89e990.PNG)

IMG_4517.PNG (こちらがnot validになります)
![IMG_4517](https://user-images.githubusercontent.com/6458565/117117829-f3c97f80-adca-11eb-8d50-897eaa613cf5.PNG)

**Comment by fgophi** [comment]
@
1. ドロップ数読み込み位置が正常ではない問題
2. 正常ではない読み込み位置で配列外を読み込みにいってエラー

のうち2.のみ修正しました

**Comment by fgophi** [comment]
@amenohimo 
1. ドロップ数読み込み位置が正常ではない問題
2. 正常ではない読み込み位置で配列外を読み込みにいってエラー

のうち2.のみ修正しました

**Comment by amenohimo** [comment]
ありがとうございます！
