### ISSUE TITLE
一部の QP(+3百万) が QP(+1) になる

### ISSUE THREAD

**Issue by amenohimo** [fgosc/fgosccnt#337]
![image](https://user-images.githubusercontent.com/6458565/141066614-6df51985-c6dc-42d3-805b-c24542b038b5.png)
https://fgojunks.max747.org/fgosccnt/results/6148a618-920d-446e-81f2-72582d4e29b7/

0027-0028
![image](https://user-images.githubusercontent.com/6458565/141067429-f1adb99f-7d27-4219-940e-80fa6f9ec6ff.png)

0027
![0027](https://user-images.githubusercontent.com/6458565/141066808-4ac196bb-6df2-43cd-847e-ab2c75e6890b.PNG)
0028
![0028](https://user-images.githubusercontent.com/6458565/141066823-157a6c59-e136-48fd-819b-f73bcc8967e5.PNG)

**Comment by fgophi** [comment]
この件、最新版で修正済みです
