### ISSUE TITLE
剣灯火が剣種火や槍灯火になる

### ISSUE THREAD

**Issue by amenohimo** [fgosc/fgosccnt#365]
![image](https://user-images.githubusercontent.com/6458565/174707852-407e8901-2be5-4d87-8f27-476aa5d72683.png)

0174
![0174](https://user-images.githubusercontent.com/6458565/174707921-9ca95f8a-5ef3-4698-8997-92f758d11552.PNG)

0666
![0666](https://user-images.githubusercontent.com/6458565/174707560-271b8666-626f-4f18-8a2f-2084b8340983.PNG)

**Comment by fgophi** [comment]
@amenohimo 
https://fgojunks.max747.org/fgosccnt/results/0f5c8f59-16b5-45f9-8b75-57ea20766e35/
ローカルで実行してもWEB版で実行しても不具合が再現しないので、おそらく実行環境が異なっていると推察します。
以下のコマンドで調べて教えてください

1. fgosccntの参照しているcommit id
```
$ git rev-parse HEAD
```

2. fgoscdata submoduleの参照しているcommit id
```
$ git submodule
```

3. ライブラリのバージョン
```
$ pip freeze
```

**Comment by amenohimo** [comment]
@fgophi
解決しました！
ありがとうございます。

以前zipで最新版を落として上書きするというgit管理外のやり方をしたためにgit pullに失敗していて、それに気づいておらず、古いバージョンを使用していたことが原因のようでした。

1. gosccntの参照しているcommit id
```
> git rev-parse HEAD
687ad1f270c923317f906d01fca2b7b0b8ed325e
```
2. fgoscdata submoduleの参照しているcommit id
```
> git submodule
 8e84c8d165e2f26fb8e0fafced31d395ee49173d fgoscdata (remotes/origin/borderd_img-fix-125-g8e84c8d)
```
3. ライブラリのバージョン
<details>
<summary> > pip freeze </summary>
appdirs==1.4.4<br>argon2-cffi==20.1.0<br>
astroid==2.11.5<br>
async-generator==1.10<br>
atomicwrites==1.4.0<br>
attrs==21.2.0<br>
autopep8==1.6.0<br>
backcall==0.2.0<br>
bleach==4.0.0<br>
certifi==2021.5.30<br>
cffi==1.14.6<br>
charset-normalizer==2.0.4<br>
click==8.1.3<br>
colorama==0.4.4<br>
colorlover==0.3.0<br>
cufflinks==0.17.3<br>
cycler==0.10.0<br>
debugpy==1.4.1<br>
decorator==5.0.9<br>
defusedxml==0.7.1<br>
dill==0.3.5.1<br>
entrypoints==0.3<br>
flake8==4.0.1<br>
Flask==2.1.2<br>
idna==3.2<br>
importlib-metadata==4.6.4<br>
iniconfig==1.1.1<br>
ipykernel==6.0.3<br>
ipython==7.26.0<br>
ipython-genutils==0.2.0<br>
ipywidgets==7.6.3<br>
isort==5.10.1<br>
itsdangerous==2.1.2<br>
japanize-matplotlib==1.1.3<br>
jedi==0.18.0<br>
Jinja2==3.0.1<br>
jsonschema==3.2.0<br>
jupyter-client==6.1.12<br>
jupyter-core==4.7.1<br>
jupyterlab-pygments==0.1.2<br>
jupyterlab-widgets==1.0.0<br>
kaleido==0.2.1<br>
kiwisolver==1.3.1<br>
lazy-object-proxy==1.7.1<br>
MarkupSafe==2.0.1<br>
matplotlib==3.4.2<br>
matplotlib-inline==0.1.2<br>
mccabe==0.6.1<br>
mistune==0.8.4<br>
MouseInfo==0.1.3<br>
nbclient==0.5.3<br>
nbconvert==6.1.0<br>
nbformat==5.1.3<br>
nest-asyncio==1.5.1<br>
notebook==6.4.2<br>
numpy==1.21.1<br>
oauthlib==3.1.1<br>
opencv-contrib-python==4.5.3.56<br>
opencv-python==4.5.3.56<br>
packaging==21.0<br>
pandas==1.3.1<br>
pandocfilters==1.4.3<br>
parso==0.8.2<br>
pgzero==1.2.1<br>
pickleshare==0.7.5<br>
Pillow==8.3.1<br>
platformdirs==2.5.2<br>
plotly==5.1.0<br>
pluggy==1.0.0<br>
prometheus-client==0.11.0<br>
prompt-toolkit==3.0.19<br>
py==1.11.0<br>
PyAutoGUI==0.9.53<br>
pycodestyle==2.8.0<br>
pycparser==2.20<br>
pyee==8.2.2<br>
pyflakes==2.4.0<br>
pygame==2.1.2<br>
PyGetWindow==0.0.9<br>
Pygments==2.9.0<br>
pylint==2.14.1<br>
PyMsgBox==1.0.9<br>
pyparsing==2.4.7<br>
pyperclip==1.8.2<br>
pyppeteer==0.2.6<br>
PyRect==0.1.4<br>
pyrsistent==0.18.0<br>
PyScreeze==0.1.28<br>
PySide2==5.15.2.1<br>
PySimpleGUI==4.46.0<br>
PySocks==1.7.1<br>
pytesseract==0.3.8<br>
pytest==7.0.1<br>
python-dateutil==2.8.2<br>
pytweening==1.0.4<br>
pytz==2021.1<br>
pywin32==301<br>
pywinpty==1.1.3<br>
pyzmq==22.2.1<br>
requests==2.26.0<br>
requests-oauthlib==1.3.0<br>
scipy==1.7.1<br>
seaborn==0.11.1<br>
Send2Trash==1.7.1<br>
shiboken2==5.15.2.1<br>
six==1.16.0<br>
tenacity==8.0.1<br>
terminado==0.10.1<br>
testpath==0.5.0<br>
toml==0.10.2<br>
tomli==2.0.1<br>
tomlkit==0.11.0<br>
tornado==6.1<br>
tqdm==4.62.1<br>
traitlets==5.0.5<br>
tweepy==3.10.0<br>
typing_extensions==4.2.0<br>
urllib3==1.26.6<br>
wcwidth==0.2.5<br>
webencodings==0.5.1<br>
websockets==9.1<br>
Werkzeug==2.1.2<br>
widgetsnbextension==3.5.1<br>
wrapt==1.14.1<br>
XlsxWriter==3.0.1<br>
zipp==3.5.0
</details>

失敗していたpull
```
> git pull true_origin master
remote: Enumerating objects: 517, done.
remote: Counting objects: 100% (247/247), done.
remote: Compressing objects: 100% (41/41), done.
Receiving objects: 100% (517/517), 236.77 KiB | 11.27 MiB/s, done. 270

Resolving deltas: 100% (257/257), completed with 9 local objects.
From https://github.com/fgosc/fgosccnt
 * branch            master     -> FETCH_HEAD        
   44de49b..b2c04e7  master     -> true_origin/master
Fetching submodule fgoscdata
From https://github.com/fgosc/fgoscdata
   55e09e3..55ae0c7  master     -> origin/master
error: The following untracked working tree files would be overwritten by merge:
        data/card/input/1/item000004.png
        data/dcnt/input/1/item3.png
        data/dcnt/input/3/item4.png
        data/dcnt/input/4/item3.png
        data/dcnt/input/5/item2.png
        data/dcnt/input/6/item3.png
        data/misc/bunyan1.png
        data/pageinfo/next.png
        requirements-dev.txt
        test_fgosccnt.py
Please move or remove them before you merge.
Aborting
Updating 687ad1f..b2c04e7

> git rev-parse HEAD         
687ad1f270c923317f906d01fca2b7b0b8ed325e
```
該当ファイル削除後
```
> git pull true_origin master
From https://github.com/fgosc/fgosccnt
 * branch            master     -> FETCH_HEAD
Updating 687ad1f..b2c04e7
Fast-forward
 background.npz                     |  Bin 13318 -> 13318 bytes
 csv2counter.py                     |   87 ++-
 data/card/input/1/item000004.png   |  Bin 0 -> 944 bytes
 data/dcnt/input/1/item3.png        |  Bin 0 -> 194 bytes
 data/dcnt/input/3/item4.png        |  Bin 0 -> 197 bytes
 data/dcnt/input/4/item3.png        |  Bin 0 -> 195 bytes
 data/dcnt/input/5/item2.png        |  Bin 0 -> 185 bytes
 data/dcnt/input/6/item3.png        |  Bin 0 -> 198 bytes
 data/item/input/0/item000006.png   |  Bin 0 -> 427 bytes
 data/item/input/0/item000011.png   |  Bin 0 -> 612 bytes
 data/item/input/120/item000005.png |  Bin 0 -> 573 bytes
 data/item/input/43/item000006.png  |  Bin 0 -> 567 bytes
 data/item/input/43/item000007.png  |  Bin 0 -> 699 bytes
 data/item/input/49/item000004.png  |  Bin 0 -> 636 bytes
 data/item/input/50/item000001.png  |  Bin 0 -> 674 bytes
 data/item/input/51/item000004.png  |  Bin 0 -> 698 bytes
 data/item/input/53/item000002.png  |  Bin 0 -> 580 bytes
 data/item/input/56/item000001.png  |  Bin 0 -> 588 bytes
 data/item/input/57/item000001.png  |  Bin 0 -> 723 bytes
 data/misc/bunyan1.png              |  Bin 0 -> 63061 bytes
 data/pageinfo/next.png             |  Bin 0 -> 26436 bytes
 fgosccnt.py                        | 1200 ++++++++++++++++++++----------------
 fgoscdata                          |    2 +-
 pageinfo.py                        |  498 ++++++++-------
 qpsplit.py                         |    8 +
 requirements-dev.txt               |    1 +
 test_fgosccnt.py                   |   75 +++
 27 files changed, 1116 insertions(+), 755 deletions(-)
 create mode 100644 data/card/input/1/item000004.png
 create mode 100644 data/dcnt/input/1/item3.png
 create mode 100644 data/dcnt/input/3/item4.png
 create mode 100644 data/dcnt/input/4/item3.png
 create mode 100644 data/dcnt/input/5/item2.png
 create mode 100644 data/dcnt/input/6/item3.png
 create mode 100644 data/item/input/0/item000006.png
 create mode 100644 data/item/input/0/item000011.png
 create mode 100644 data/item/input/120/item000005.png
 create mode 100644 data/item/input/43/item000006.png
 create mode 100644 data/item/input/43/item000007.png
 create mode 100644 data/item/input/49/item000004.png
 create mode 100644 data/item/input/50/item000001.png
 create mode 100644 data/item/input/51/item000004.png
 create mode 100644 data/item/input/53/item000002.png
 create mode 100644 data/item/input/56/item000001.png
 create mode 100644 data/item/input/57/item000001.png
 create mode 100644 data/misc/bunyan1.png
 create mode 100755 data/pageinfo/next.png
 create mode 100644 requirements-dev.txt
 create mode 100644 test_fgosccnt.py

> git rev-parse master
b2c04e74b644d55876f28204251821a8e18d27d9

> git submodule update       
Submodule path 'fgoscdata': checked out '55ae0c79636c03a093a91adfdc096a5a31adcded'

> git submodule       
 55ae0c79636c03a093a91adfdc096a5a31adcded fgoscdata (remotes/origin/HEAD)

> python makeitem.py
> python makechest.py
> python makecard.py
> python makedcnt.py

C:\Users\ameno\fgosccnt-batch-programs-for-Windows>"C:\Users\ameno\scoop\apps\python\3.9.6\python.exe" "C:\Users\ameno\fgosccnt\fgosccnt.py"  O:\Desktop\test_im\0666.PNG O:\Desktop\test_im\0174.PNG --timeout 35  1>"C:\Users\ameno\Documents\FGO\csv"sccnt2022-06_25-21_23_56.csv
```

![image](https://user-images.githubusercontent.com/6458565/175773368-c32decae-a962-4a03-95ca-36fbaf03da61.png)

**Comment by fgophi** [comment]
解決したということでほっとしました
