### ISSUE TITLE
not valid になる

### ISSUE THREAD

**Issue by amenohimo** [fgosc/fgosccnt#367]
```
>"C:\Users\ameno\scoop\apps\python\3.9.6\python.exe" fgosccnt.py  304.PNG  --timeout 35  
__main__ <fgosccnt.py-L2637> [ERROR] 304.PNG
__main__ <fgosccnt.py-L2638> [ERROR] ''
Traceback (most recent call last):
  File "C:\Users\ameno\fgosccnt\fgosccnt.py", line 2544, in get_output
    sc = ScreenShot(args, img_rgb,
  File "C:\Users\ameno\fgosccnt\fgosccnt.py", line 463, in __init__
    dropitem = Item(args, i, prev_item, item_img_rgb, item_img_gray,
  File "C:\Users\ameno\fgosccnt\fgosccnt.py", line 1175, in __init__
    self.identify_item(args, prev_item, svm_card,
  File "C:\Users\ameno\fgosccnt\fgosccnt.py", line 1217, in identify_item
    self.name = item_name[self.id]
KeyError: ''
```
![304](https://user-images.githubusercontent.com/6458565/187057278-14582b6a-cfdf-454d-87cd-2281b7a7a6ab.PNG)
![314](https://user-images.githubusercontent.com/6458565/187057281-2f65ff38-c736-4541-a85f-4ca855242712.PNG)
![350](https://user-images.githubusercontent.com/6458565/187057282-53a6a348-5ac6-4b3b-b627-662362b0168b.PNG)
![568](https://user-images.githubusercontent.com/6458565/187057283-3442b529-a755-4200-85b8-397082ceda77.PNG)
![598](https://user-images.githubusercontent.com/6458565/187057285-f6e3a86b-93aa-425c-958c-f9d42bf6dabe.PNG)

**Comment by fgophi** [comment]
@amenohimo 
修正しました

https://fgojunks.max747.org/fgosccnt/results/e190966e-58ae-4330-983d-78ea118a6d3e/

カード種類判別機で99(アイテム判定できない)と判定しないといけないところを4(EXP Up)と誤判定してたせいです

**Comment by amenohimo** [comment]
直りました
ありがとうございます！
